version: "3.8"

services:
  spring:
    build:
      context: .
      dockerfile: Dockerfile
    image: springboot-backend
    ports:
      - "8080:8080"
    volumes:
      - upload:/app/uploads
      # Ensure uploads directory is accessible in Docker
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb+srv://root:root@springdb.tpk1b.mongodb.net/?retryWrites=true&w=majority&appName=SpringDB
      - SPRING_DATA_MONGODB_DATABASE=NEWINSTANCE
    command: ["java", "-jar", "app.jar"]  # Run Spring Boot normally

  react:
    build:
      context: ../../OneDrive/Desktop/MERN_PROJECT/REACTSPRING/reactTS
      dockerfile: Dockerfile
    image: react-docker
    ports:
      - "3000:3000"
    volumes:
      - ../../OneDrive/Desktop/MERN_PROJECT/REACTSPRING/reactTS:/app  # Watch React files
      - /app/node_modules  # Prevent overwriting node_modules
    environment:
      - REACT_APP_API_URL=http://spring:8080  # Correct backend API URL inside Docker
    command: npm run dev -- --host  # Enable hot reloading in Vite
    depends_on:
      - spring

volumes:
  upload:


